import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'A homework assignment for the twreporter interview',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
